# This file was generated by go2nix.
{ stdenv, lib, fetchFromGitHub, fetchhg }:

let
  goDeps = [
    {
      root = "code.google.com/p/goprotobuf";
      src = fetchhg {
        url = "https://code.google.com/p/goprotobuf";
        rev = "267";
        sha256 = "0kamslfmxs6hi9ww52izmsq48ldaf67xawwhzwwdsbslhv0b9lf7";
      };
    }
    {
      root = "github.com/golang/glog";
      src = fetchFromGitHub {
        owner = "golang";
        repo = "glog";
        rev = "44145f04b68cf362d9c4df2182967c2275eaefed";
        sha256 = "1k7sf6qmpgm0iw81gx2dwggf9di6lgw0n54mni7862hihwfrb5rq";
      };
    }
    {
      root = "github.com/golang/protobuf";
      src = fetchFromGitHub {
        owner = "golang";
        repo = "protobuf";
        rev = "5677a0e3d5e89854c9974e1256839ee23f8233ca";
        sha256 = "18dzxmy0gfjnwa9x8k3hv9calvmydv0dnz1iibykkzd20gw4l85v";
      };
    }
    {
      root = "github.com/matttproud/golang_protobuf_extensions";
      src = fetchFromGitHub {
        owner = "matttproud";
        repo = "golang_protobuf_extensions";
        rev = "7a864a042e844af638df17ebbabf8183dace556a";
        sha256 = "0vb547ljhwj0qkmcj6pg47iqzy69p6isaryaph8wmlqwsvbx3di4";
      };
    }
    {
      root = "github.com/miekg/dns";
      src = fetchFromGitHub {
        owner = "miekg";
        repo = "dns";
        rev = "b65f52f3f0dd1afa25cbbf63f8e7eb15fb5c0641";
        sha256 = "1hwia27rmyc9373g4dwc9z0jkka3w2i0i2zic4ybk9ac9limp9jv";
      };
    }
    {
      root = "github.com/onsi/ginkgo";
      src = fetchFromGitHub {
        owner = "onsi";
        repo = "ginkgo";
        rev = "f7bd156ea78c26c8213198b0840488dba9eea51c";
        sha256 = "1443fmgsrs312rj6kcflynk050al2l8am0nqlga4jlczhvygjsf7";
      };
    }
    {
      root = "github.com/onsi/gomega";
      src = fetchFromGitHub {
        owner = "onsi";
        repo = "gomega";
        rev = "8adf9e1730c55cdc590de7d49766cb2acc88d8f2";
        sha256 = "1rf6cxn50d1pji3pv4q372s395r5nxwcgp405z2r2mfdkri4v3w4";
      };
    }
    {
      root = "github.com/prometheus/client_golang";
      src = fetchFromGitHub {
        owner = "prometheus";
        repo = "client_golang";
        rev = "a9bdd32c7193ea752e863392e37f70d1f6b32bc1";
        sha256 = "06pp323cmzy53y1bnyqvll4dlr46hvigq1536igfgbgmmnpiymb5";
      };
    }
    {
      root = "github.com/prometheus/client_model";
      src = fetchFromGitHub {
        owner = "prometheus";
        repo = "client_model";
        rev = "fa8ad6fec33561be4280a8f0514318c79d7f6cb6";
        sha256 = "11a7v1fjzhhwsl128znjcf5v7v6129xjgkdpym2lial4lac1dhm9";
      };
    }
    {
      root = "github.com/prometheus/haproxy_exporter";
      src = fetchFromGitHub {
        owner = "prometheus";
        repo = "haproxy_exporter";
        rev = "6ee6d1df3e68ed73df37c9794332b2594e4da45d";
        sha256 = "0lbwv6jsdfjd9ihiky3lq7d5rkxqjh7xfaziw8i3w34a38japlpr";
      };
    }
    {
      root = "github.com/prometheus/procfs";
      src = fetchFromGitHub {
        owner = "prometheus";
        repo = "procfs";
        rev = "92faa308558161acab0ada1db048e9996ecec160";
        sha256 = "0kaw81z2yi45f6ll6n2clr2zz60bdgdxzqnxvd74flynz4sr0p1v";
      };
    }
    {
      root = "github.com/prometheus/prometheus";
      src = fetchFromGitHub {
        owner = "prometheus";
        repo = "prometheus";
        rev = "3d0fb516482986d166868c37c7b3cbacdb221069";
        sha256 = "03jxfxigb3i6ssk83q24rf21n44wnhzy900p1jgynis50m6nb28p";
      };
    }
    {
      root = "github.com/syndtr/goleveldb";
      src = fetchFromGitHub {
        owner = "syndtr";
        repo = "goleveldb";
        rev = "e9e2c8f6d3b9c313fb4acaac5ab06285bcf30b04";
        sha256 = "0vg3pcrbdhbmanwkc5njxagi64f4k2ikfm173allcghxcjamrkwv";
      };
    }
    {
      root = "github.com/syndtr/gosnappy";
      src = fetchFromGitHub {
        owner = "syndtr";
        repo = "gosnappy";
        rev = "ce8acff4829e0c2458a67ead32390ac0a381c862";
        sha256 = "0ywa52kcii8g2a9lbqcx8ghdf6y56lqq96sl5nl9p6h74rdvmjr7";
      };
    }
  ];

in

stdenv.mkDerivation rec {
  name = "go-deps";

  buildCommand =
    lib.concatStrings
      (map (dep: ''
              mkdir -p $out/src/`dirname ${dep.root}`
              ln -s ${dep.src} $out/src/${dep.root}
            '') goDeps);
}
